/*
 * generated by Xtext 2.22.0
 */
package org.xtuml.bp.xtext.masl.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtuml.bp.xtext.masl.MASLRuntimeModule
import org.xtuml.bp.xtext.masl.MASLStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MASLIdeSetup extends MASLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MASLRuntimeModule, new MASLIdeModule))
	}
	
}
